### ISSUE TITLE
Having queries in lighthouse automation below are :

### ISSUE THREAD

**Issue by devyani735** [gowthamraj198/Lighthouse#3]
1. Reports is locally available, how can we share with other ? 
2. If I want to display string like 'Lighthouse testing for this url : {URL}', how can we do it? 
3. After generating report can we generate in excel ?
4. Can we integrate this code with jenkins ?

Thanks in advance !
Devyani

**Comment by gowthamraj198** [comment]
All are possible. But you need to add / modify the code according to your needs.

**Comment by gowthamraj198** [comment]
closing as this is not an issue but kind of enhancement
